    <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
    <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
    <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
    <!--[if IE 9]> <html class="no-js ie9 oldie" lang="en"> <![endif]-->
    <meta charset="utf-8">
    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="">
    <!-- ============ Google fonts ============ -->
    <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet'
        type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300,800'
        rel='stylesheet' type='text/css' />
    <!-- ============ Add custom CSS here ============ -->
    <link href="Content/css/Login/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="Content/css/Login/style.css" rel="stylesheet" type="text/css" />
    <link href="Content/css/Login/font-awesome.css" rel="stylesheet" type="text/css" />
	<link rel="shortcut icon" href="Content/Images/favicon.ico" type="image/x-icon">
	<link rel="icon" href="Content/Images/favicon.ico" type="image/x-icon">