<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="../">
                        <img src="Content/Images/connecting-bes-tmarkets-agexport-logotipo-bn.png" height="140px" width="300px" alt="" />
                    </a>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder">
                        <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span
                            class="icon-bar"></span><span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse navbar-menubuilder">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="../">INICIO</a> </li>
                        <li><a href="#">POLITICAS</a> </li>
                        <li><a href="#">CONTACTENOS</a> </li>
                    </ul>
                </div>
            </div>
        </div>